--- 
- 
  become_method: sudo
  become_user: root
  hosts: all
  remote_user: root
  tasks: 
    - 
      apt: 
        update_cache: true
        upgrade: true
      become: true
      name: "Apt-get update & upgrade"
    - 
      apt: 
        name: git
        state: present
      name: "Install git"
    - 
      apt: 
        name: npm
        state: present
      name: "install npm"
    - 
      apt: 
        name: xinetd
        state: present
      name: "install xinetd"
    - 
      command: 
        cmd: "wget http://192.168.0.231:8081/cmk/check_mk/agents/check-mk-agent_2.0.0p5-1_all.deb"
      name: "wget checkmk agent"
    - 
      command: 
        cmd: "dpkg -i check-mk-agent_2.0.0p5-1_all.deb"
      name: "dpkg checkmk agent"
    - 
      name: "check if project folder exists"
      register: stat_project
      stat: 
        path: /project
    - 
      become: true
      command: 
        cmd: "rm -r /project"
      name: "delete if project folder exists"
      when: stat_project.stat.exists
    - 
      command: 
        cmd: "mkdir /project"
      name: "create /project folder"
    - 
      git: 
        dest: /project
        force: true
        repo: "https://github.com/grYs51/ScoreSaberSomethingIonic.git"
      name: "download repo"
    -
      apt:
        name: apache2
        state: latest
      name: Install Apache
      become: true
    - 
      become: true
      command: 
        cmd: "npm install -g @ionic/cli"
      name: "Install Ionic"
    - 
      become: true
      command: 
        cmd: "npm install -g cordova"
      name: "Install Cordova"

    - 
      become: true
      npm: 
        path: "/project/ScoreSaberSomethingIonic"
      name: "Install modules"
    -
      name: "update audit fix app"
      command:
        chdir: /project/ScoreSaberSomethingIonic
        cmd: "npm audit fix"
    -
      name: "building app"
      command:
        chdir: /project/ScoreSaberSomethingIonic
        cmd: "ionic build"

    - name: "delete apache stock website"
      file:
        path: "var/www/html"
        state: absent
    
    - name: "move build to apache"
      command:
          cmd: mv /project/ScoreSaberSomethingIonic/www /var/www/html

    - name: "restart apache"
      command:
        cmd: "service apache2 restart"
      become: true
          